# Numpy  Intro.....................

- what is an array
-    An array is a data structure that stores a collection of elements, each identified by at least one array index or key. It is used to store a fixed-size sequential collection of elements of the same type.






In [1]:
import numpy as np

In [2]:
a= np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
a[0] = 10
a

array([10,  1,  2,  3,  4,  5])

In [4]:
b = a[3:]
b
b[0] = 40
a

array([10,  1,  2, 40,  4,  5])

In [5]:
a =np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape

(3, 4)

#### Creating Array with Numpy

In [6]:
a = np.array([1,2,3,4,5,6])
b =np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])

In [7]:
a.shape

(6,)

In [8]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


(2, 6)

#### Initialize arrays

In [9]:
zeros =np.zeros((3,4))    
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
ones =np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- 02 np

In [11]:
empty =np.empty((2,3))
print(empty)

[[0.00000000e+000 0.00000000e+000 1.01632743e-311]
 [1.01632743e-311 8.39911598e-323 1.08694442e-322]]


In [12]:
print(empty[1])

[1.01632743e-311 8.39911598e-323 1.08694442e-322]


In [13]:
x =np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [14]:
even =np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [15]:
odd =np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [16]:
# specific differnce between number 
diff =np.arange(0,23,0.516)
diff

array([ 0.   ,  0.516,  1.032,  1.548,  2.064,  2.58 ,  3.096,  3.612,
        4.128,  4.644,  5.16 ,  5.676,  6.192,  6.708,  7.224,  7.74 ,
        8.256,  8.772,  9.288,  9.804, 10.32 , 10.836, 11.352, 11.868,
       12.384, 12.9  , 13.416, 13.932, 14.448, 14.964, 15.48 , 15.996,
       16.512, 17.028, 17.544, 18.06 , 18.576, 19.092, 19.608, 20.124,
       20.64 , 21.156, 21.672, 22.188, 22.704])

In [17]:
# linspace linear trends 
lin =np.linspace(0,20,num=10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [18]:
lin = np.linspace(0,10,num=1700000)
lin

array([0.00000000e+00, 5.88235640e-06, 1.17647128e-05, ...,
       9.99998824e+00, 9.99999412e+00, 1.00000000e+01])

In [19]:
lin =np.linspace(0,10,num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
# defind a data type of array 
x =np.arange(0, 22.6, 1.5, dtype=np.float64)
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5])

In [21]:
a =np.array([1,2,3,4])
b =np.array([5,6,7,8])


In [22]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Concatenate 2D Arrays 

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [24]:
# concitenate 2d arrsy 
c =np.concatenate((x,y))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
w =np.array([[5,1], [7,1]])

In [26]:
z1 =np.concatenate((x, w))

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [30]:
array_example.ndim

3

In [31]:
len(array_example)

3

In [32]:
array_example.dtype

dtype('int64')

In [33]:
array_example.shape

(3, 2, 4)

In [34]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [35]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a =np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [38]:
a[np.newaxis, :].shape


(1, 8)