# Numpy  Intro.....................

- what is an array
-    An array is a data structure that stores a collection of elements, each identified by at least one array index or key. It is used to store a fixed-size sequential collection of elements of the same type.






In [1]:
import numpy as np

In [2]:
a= np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
a[0] = 10
a

array([10,  1,  2,  3,  4,  5])

In [4]:
b = a[3:]
b
b[0] = 40
a

array([10,  1,  2, 40,  4,  5])

In [5]:
a =np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape

(3, 4)

#### Creating Array with Numpy

In [6]:
a = np.array([1,2,3,4,5,6])
b =np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])

In [7]:
a.shape

(6,)

In [8]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


(2, 6)

#### Initialize arrays

In [9]:
zeros =np.zeros((3,4))    
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
ones =np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- 02 np

In [11]:
empty =np.empty((2,3))
print(empty)

[[1.20129000e-075 6.40302754e+170 2.92806773e-057]
 [1.04739739e+165 9.34599605e-307 5.63234836e-322]]


In [12]:
print(empty[1])

[1.04739739e+165 9.34599605e-307 5.63234836e-322]


In [14]:
x =np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [16]:
even =np.arange(0,23,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])